### ISSUE TITLE
[Bug]: Loading consul configuration from environment fails in 1.7.14.4

### ISSUE THREAD

**Issue by tdeangelis** [G-Research/consuldotnet#359]
### Describe the bug

In 1.7.14.4 when loading the the consul configuration from the environment variable CONSUL_HTTP_ADDR it does not parse the variable correctly when using a string based host name for the consul address.

In 1.7.14.3 the following example setting would parse properly as the host name and port:
CONSUL_HTTP_ADDR = consul:8500

In 1.7.14.4 this get's parsed out as:

- Host is left default (127.0.0.1)
- Path is set to 8500
- Port is set to -1

This is caused by the [Uri.TryCreate](https://github.com/G-Research/consuldotnet/blob/62a5a263dc6cbc40e2da94a147c38daf45259e1b/Consul/Client.cs#L167) reading that string as:

- Scheme is set to consul
- AbsolutePath is set to 8500

### Steps To Reproduce

1. Set your CONSUL_HTTP_ADDR to a DNS named consul server with port (consul:8500)
2. Set your CONSUL_HTTP_TOKEN to a valid token for that consul server
3. New up the ConsulClient object using the default constructor.
4. Fetch any items from the KV (await client.KV.List("anykey");)
5. Notice Exception:
Exception has occurred: CLR/System.Net.Http.HttpRequestException
An exception of type 'System.Net.Http.HttpRequestException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'No connection could be made because the target machine actively refused it. (127.0.0.1:80)'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()
   at System.Net.Http.HttpConnectionPool.<ConnectToTcpHostAsync>d__104.MoveNext()

### Expected behavior

Legacy URI parsing behavior for environment variables should be maintained or this should be called out as a breaking change in this version.

### Environment

- OS:       Windows
- Consul Version:    1.19.1
- consultdotnet Version   1.7.14.4

**Comment by harvzor** [comment]
I'm experiencing the same bug

Seems likely this was introduced in https://github.com/G-Research/consuldotnet/pull/333

**Comment by marcin-krystianc** [comment]
> I'm experiencing the same bug
> 
> Seems likely this was introduced in #333

I believe it should be fixed with https://github.com/G-Research/consuldotnet/pull/395, the fix is included in v1.7.14.5.
@harvzor @tdeangelis Can you confirm if it is being resolved in the latest version?

**Comment by tdeangelis** [comment]
I tried it with v1.7.14.5 and it still throws the same error: 

Exception has occurred: CLR/System.Net.Http.HttpRequestException
An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in System.Private.CoreLib.dll: 'No connection could be made because the target machine actively refused it. (127.0.0.1:8500)'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()
   at System.Net.Http.HttpConnectionPool.<ConnectToTcpHostAsync>d__104.MoveNext()

For reference the environment variable is defined as follows:
CONSUL_HTTP_ADDR               consul.stage.somecompany.com:8500

**Comment by harvzor** [comment]
https://github.com/G-Research/consuldotnet/pull/401 seems to solve the issue 💯

**Comment by marcin-krystianc** [comment]
Fix in 1.7.14.6
